name: Convert MD to PDF

on:
  push:
    branches: [ main ]

permissions:
  contents: write

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Install Dependencies
        run: |
          # Install Pandoc
          wget https://github.com/jgm/pandoc/releases/download/2.9.2.1/pandoc-2.9.2.1-1-amd64.deb
          sudo dpkg -i pandoc-2.9.2.1-1-amd64.deb
          # Install WKHTMLTOPDF
          sudo apt-get install xvfb libfontconfig wkhtmltopdf
      
      - name: Create File List
        id: files_list
        run: |
          mkdir output
          echo "::set-output name=files::$(printf '"%s" ' *.md)"
          
      - name: Run Pandoc
        run: |
          pandoc -t html --pdf-engine=wkhtmltopdf --pdf-engine-opt=--enable-local-file-access --css=layouts/worksheet.css --output=output/result.pdf ${{ steps.files_list.outputs.files }}
          
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: output
          path: output
      
      - name: Commit
        run: |
          git add .
          # Force the build to succeed, even if no files were changed
          git commit -m 'Export to PDF' || true
          git push	
